-- Ensure the canonical notification schema for helper and household workflow events.
-- This migration is additive: on databases that already have public.notifications,
-- it preserves the table and all rows and only ensures its FK, check, and indexes.
BEGIN;

CREATE TABLE IF NOT EXISTS public.notifications (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id bigint NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    type              smallint NOT NULL,
    title             varchar NOT NULL,
    body              varchar NOT NULL,
    link_path         varchar,
    source_type       smallint NOT NULL,
    source_id         bigint NOT NULL,
    is_read           boolean NOT NULL DEFAULT false,
    created_at_utc    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_notification_type CHECK (type BETWEEN 1 AND 9)
);

-- The application omits id when inserting a notification. Preserve any existing
-- ID default; where none exists, add identity generation and advance its sequence
-- past existing IDs without updating or rewriting notification rows.
DO $migration$
DECLARE
    current_max_id bigint;
    identity_sequence text;
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'notifications'
          AND column_name = 'id'
          AND is_identity = 'NO'
          AND column_default IS NULL
    ) THEN
        ALTER TABLE public.notifications
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

        SELECT max(id) INTO current_max_id FROM public.notifications;
        identity_sequence := pg_get_serial_sequence('public.notifications', 'id');
        IF identity_sequence IS NOT NULL THEN
            PERFORM setval(
                identity_sequence::regclass,
                greatest(coalesce(current_max_id, 0), 1),
                current_max_id IS NOT NULL
            );
        END IF;
    END IF;
END;
$migration$;

-- The existing table may already have the equivalent FK under another name.
DO $migration$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        WHERE c.conrelid = 'public.notifications'::regclass
          AND c.contype = 'f'
          AND c.confrelid = 'public.users'::regclass
          AND c.conkey = ARRAY[(
              SELECT a.attnum
              FROM pg_attribute a
              WHERE a.attrelid = 'public.notifications'::regclass
                AND a.attname = 'recipient_user_id'
                AND NOT a.attisdropped
          )]::smallint[]
          AND c.confkey = ARRAY[(
              SELECT a.attnum
              FROM pg_attribute a
              WHERE a.attrelid = 'public.users'::regclass
                AND a.attname = 'id'
                AND NOT a.attisdropped
          )]::smallint[]
          AND c.confdeltype = 'c'
    ) THEN
        ALTER TABLE public.notifications
            ADD CONSTRAINT fk_notifications_recipient_user
            FOREIGN KEY (recipient_user_id)
            REFERENCES public.users (id)
            ON DELETE CASCADE
            NOT VALID;
    END IF;
END;
$migration$;

-- Preserve the established 1-9 range, including type 9, whose meaning is not
-- assigned by this repository's helper notification events.
DO $migration$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'public.notifications'::regclass
          AND conname = 'ck_notification_type'
    ) THEN
        ALTER TABLE public.notifications
            ADD CONSTRAINT ck_notification_type
            CHECK (type BETWEEN 1 AND 9)
            NOT VALID;
    END IF;
END;
$migration$;

-- Validate the canonical recipient FK and type range without rewriting rows.
DO $migration$
DECLARE
    constraint_name text;
BEGIN
    FOR constraint_name IN
        SELECT c.conname
        FROM pg_constraint c
        WHERE c.conrelid = 'public.notifications'::regclass
          AND c.contype = 'f'
          AND c.confrelid = 'public.users'::regclass
          AND c.conkey = ARRAY[(
              SELECT a.attnum
              FROM pg_attribute a
              WHERE a.attrelid = 'public.notifications'::regclass
                AND a.attname = 'recipient_user_id'
                AND NOT a.attisdropped
          )]::smallint[]
          AND c.confkey = ARRAY[(
              SELECT a.attnum
              FROM pg_attribute a
              WHERE a.attrelid = 'public.users'::regclass
                AND a.attname = 'id'
                AND NOT a.attisdropped
          )]::smallint[]
          AND c.confdeltype = 'c'
          AND NOT c.convalidated
    LOOP
        EXECUTE format('ALTER TABLE public.notifications VALIDATE CONSTRAINT %I', constraint_name);
    END LOOP;

    IF EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'public.notifications'::regclass
          AND conname = 'ck_notification_type'
          AND NOT convalidated
    ) THEN
        ALTER TABLE public.notifications VALIDATE CONSTRAINT ck_notification_type;
    END IF;
END;
$migration$;

CREATE INDEX IF NOT EXISTS ix_notif_inbox
    ON public.notifications (recipient_user_id, is_read, created_at_utc DESC);

CREATE UNIQUE INDEX IF NOT EXISTS ux_notif_dedupe
    ON public.notifications (recipient_user_id, source_type, source_id, type);

COMMIT;
